# Generated by Django 6.0.7 on 2026-07-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
